#!/usr/bin/env bash
# Configure Google Maps API key across Flutter mobile platforms (not committed to git).
#
# Usage:
#   bash scripts/setup-google-maps.sh
#   GOOGLE_MAPS_API_KEY=your_key bash scripts/setup-google-maps.sh
#
# After running, launch with an optional dart-define for web fallback checks:
#   flutter run --dart-define=GOOGLE_MAPS_API_KEY=your_key
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOBILE="$ROOT/apps/mobile"
ANDROID_PROPS="$MOBILE/android/local.properties"
IOS_PLIST="$MOBILE/ios/Runner/Info.plist"
WEB_INDEX="$MOBILE/web/index.html"

if [ -n "${GOOGLE_MAPS_API_KEY:-}" ]; then
  API_KEY="$GOOGLE_MAPS_API_KEY"
else
  read -r -p "Enter Google Maps API key: " API_KEY
fi

if [ -z "$API_KEY" ]; then
  echo "No API key provided. Platforms will use empty/placeholder values and the web fallback map."
  exit 0
fi

# Android — local.properties is gitignored
mkdir -p "$(dirname "$ANDROID_PROPS")"
if [ -f "$ANDROID_PROPS" ]; then
  if grep -q '^google.maps.api.key=' "$ANDROID_PROPS"; then
    if [[ "$(uname)" == "Darwin" ]]; then
      sed -i '' "s|^google.maps.api.key=.*|google.maps.api.key=$API_KEY|" "$ANDROID_PROPS"
    else
      sed -i "s|^google.maps.api.key=.*|google.maps.api.key=$API_KEY|" "$ANDROID_PROPS"
    fi
  else
    printf '\n# Google Maps (see scripts/setup-google-maps.sh)\ngoogle.maps.api.key=%s\n' "$API_KEY" >> "$ANDROID_PROPS"
  fi
else
  cat > "$ANDROID_PROPS" <<EOF
# Generated by scripts/setup-google-maps.sh — do not commit
google.maps.api.key=$API_KEY
EOF
fi
echo "Updated $ANDROID_PROPS"

# iOS — Info.plist GoogleMapsApiKey
if [[ "$(uname)" == "Darwin" ]]; then
  /usr/libexec/PlistBuddy -c "Set :GoogleMapsApiKey $API_KEY" "$IOS_PLIST" 2>/dev/null \
    || /usr/libexec/PlistBuddy -c "Add :GoogleMapsApiKey string $API_KEY" "$IOS_PLIST"
  echo "Updated $IOS_PLIST (GoogleMapsApiKey)"
else
  echo "Skipping iOS plist update (PlistBuddy requires macOS). Set GoogleMapsApiKey in $IOS_PLIST manually."
fi

# Web — Maps JavaScript API script tag
if grep -q 'maps.googleapis.com/maps/api/js' "$WEB_INDEX"; then
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "s|https://maps.googleapis.com/maps/api/js?key=[^\"']*|https://maps.googleapis.com/maps/api/js?key=$API_KEY|" "$WEB_INDEX"
  else
    sed -i "s|https://maps.googleapis.com/maps/api/js?key=[^\"']*|https://maps.googleapis.com/maps/api/js?key=$API_KEY|" "$WEB_INDEX"
  fi
  echo "Updated $WEB_INDEX"
else
  echo "Warning: could not find Maps script tag in $WEB_INDEX"
fi

cat <<EOF

Google Maps key configured.

Optional Flutter dart-define (web fallback / MapsConstants.isConfigured):
  flutter run --dart-define=GOOGLE_MAPS_API_KEY=$API_KEY

Without a key, marketplace maps use the built-in fallback UI on web and empty keys on native.

EOF
