import { EiBillingQueueStatus, UserRole } from '../../generated/prisma/client';

export const DEFAULT_EI_UNIT_RATE = 60;

export function computeEiBilledAmount(units: number): number {
  return units * DEFAULT_EI_UNIT_RATE;
}

export const EI_VALIDATION_CODES = {
  SESSION_NOT_COMPLETED: 'SESSION_NOT_COMPLETED',
  SOAP_NOTE_UNSIGNED: 'SOAP_NOTE_UNSIGNED',
  AGENCY_PROFILE_INCOMPLETE: 'AGENCY_PROFILE_INCOMPLETE',
  AGENCY_BAA_MISSING: 'AGENCY_BAA_MISSING',
  PROVIDER_NOT_ENROLLED: 'PROVIDER_NOT_ENROLLED',
  PROVIDER_CREDENTIAL_INACTIVE: 'PROVIDER_CREDENTIAL_INACTIVE',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  SCR_CLEARANCE_EXPIRED: 'SCR_CLEARANCE_EXPIRED',
  CASE_PROFILE_MISSING: 'CASE_PROFILE_MISSING',
  IFSP_AUTH_MISSING: 'IFSP_AUTH_MISSING',
  AUTH_DATE_OUT_OF_RANGE: 'AUTH_DATE_OUT_OF_RANGE',
  MEDICAID_CIN_MISSING: 'MEDICAID_CIN_MISSING',
  CONSENT_NOT_GRANTED: 'CONSENT_NOT_GRANTED',
  DUPLICATE_SESSION_BILLING: 'DUPLICATE_SESSION_BILLING',
  UNITS_MISMATCH: 'UNITS_MISMATCH',
  EVV_NOT_VERIFIED: 'EVV_NOT_VERIFIED',
  SERVICE_DATE_MISSING: 'SERVICE_DATE_MISSING',
} as const;

export type EiValidationCode =
  (typeof EI_VALIDATION_CODES)[keyof typeof EI_VALIDATION_CODES];

export const EI_QUEUE_TRANSITIONS: Record<
  EiBillingQueueStatus,
  EiBillingQueueStatus[]
> = {
  DRAFT_INCOMPLETE: ['MISSING_INFORMATION', 'READY_AGENCY_REVIEW', 'ARCHIVED'],
  MISSING_INFORMATION: ['DRAFT_INCOMPLETE', 'READY_AGENCY_REVIEW', 'ARCHIVED'],
  READY_AGENCY_REVIEW: [
    'MISSING_INFORMATION',
    'READY_BILLING_VALIDATION',
    'ARCHIVED',
  ],
  READY_BILLING_VALIDATION: [
    'MISSING_INFORMATION',
    'READY_AGENCY_REVIEW',
    'READY_AUTHORIZED_SUBMISSION',
    'ARCHIVED',
  ],
  READY_AUTHORIZED_SUBMISSION: [
    'READY_BILLING_VALIDATION',
    'SUBMITTED',
    'ARCHIVED',
  ],
  SUBMITTED: ['REJECTED', 'DENIED', 'PAID', 'CORRECTION_NEEDED'],
  REJECTED: ['CORRECTION_NEEDED', 'RESUBMITTED', 'ARCHIVED'],
  DENIED: ['CORRECTION_NEEDED', 'ARCHIVED'],
  CORRECTION_NEEDED: ['MISSING_INFORMATION', 'READY_BILLING_VALIDATION', 'RESUBMITTED'],
  RESUBMITTED: ['SUBMITTED', 'REJECTED', 'DENIED', 'PAID'],
  PAID: ['ARCHIVED'],
  ARCHIVED: [],
};

export const EI_QUEUE_ROLE_PERMISSIONS: Partial<
  Record<EiBillingQueueStatus, UserRole[]>
> = {
  READY_AGENCY_REVIEW: ['AGENCY_ADMIN', 'PLATFORM_ADMIN'],
  READY_BILLING_VALIDATION: ['BILLING_STAFF', 'PLATFORM_ADMIN'],
  READY_AUTHORIZED_SUBMISSION: ['BILLING_STAFF', 'AGENCY_ADMIN', 'PLATFORM_ADMIN'],
  SUBMITTED: ['BILLING_STAFF', 'PLATFORM_ADMIN'],
};
